### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by I-No-oNe** [Pan4ur/ThunderHack-Recode#105]
```yml
[15:25:32] [Thread-29/ERROR]:
 Uncaught exception in thread "Thread-29"
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_18112()" because "thunder.hack.modules.combat.AutoCrystal.mc.field_1687" is null
	at thunder.hack.modules.combat.AutoCrystal.getPossibleCrystals(AutoCrystal.java:607) ~[thunderhack-1.3%20(4).jar:?]
	at thunder.hack.modules.combat.AutoCrystal.getCrystalToExplode(AutoCrystal.java:649) ~[thunderhack-1.3%20(4).jar:?]
	at thunder.hack.modules.combat.AutoCrystal$BreakThread.run(AutoCrystal.java:1049) ~[thunderhack-1.3%20(4).jar:?]
```
after that(the code i mentioned here) ,the client is crashing (im also using metor), it`s important to mention that its effect my screen with random blinks. pretty good and working client but ***please fix the crash!***

**Comment by Pan4ur** [comment]
Can you send full log?

**Comment by Pan4ur** [comment]
Hmm

**Comment by Pan4ur** [comment]
Minecraft crashes before the error appears

**Comment by I-No-oNe** [comment]
ik

**Comment by I-No-oNe** [comment]
maybe it`s something with my gpu?

**Comment by I-No-oNe** [comment]
i will check it rn

**Comment by I-No-oNe** [comment]
https://mclo.gs/A5Sd4S9

**Comment by I-No-oNe** [comment]
the game just froze so i stopped it

**Comment by I-No-oNe** [comment]
and my screen still blink after the crash (it's not happening before the crash)

**Comment by Pan4ur** [comment]
Are you using AutoTrap?

**Comment by I-No-oNe** [comment]
maybe this will [help u](https://mclo.gs/vyEZdkp)

**Comment by I-No-oNe** [comment]
(another log file)

**Comment by I-No-oNe** [comment]
@Pan4ur any idea?

**Comment by I-No-oNe** [comment]
`Ty!`
