### ISSUE TITLE
Краш

### ISSUE THREAD

**Issue by CrasherAHah** [Pan4ur/ThunderHack-Recode#241]
Я установил чит и forge версию для майнкрафта 1.20.4
запустил через Тлаунчер версию forge 1.20.4 и вылетела ошибка с консолью. Текст ошибки:
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric-api, any version.
More details:
	 - Mod 'ThunderHack' (thunderhack) 1.4 requires any version of fabric-api, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by CvatiyMlinec** [comment]
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/138506119/09cfdeb6-69db-477f-bc63-12ec74e838bd)
💀

**Comment by CrasherAHah** [comment]
Что это значит? Чит предназначен для версии 1.20.4, а текст в консоли советует мне скачать фабрик-апи другой версии зачем то, а еще говорит, что мод Tunderhawk требует любой версии фабрик апи которая отсутствует, а в этом предложении я ничего не понял
