### ISSUE TITLE
Крашит при использовании тотема у врага с включенным PopChams.

### ISSUE THREAD

**Issue by alexsovi** [Pan4ur/ThunderHack-Recode#426]
Думал, что доиграю дуэль, а так уже второй раз крашнулся майн.

**Steps to reproduce:**
1. Включить модуль PopChams из render.
2. Зайти на любой сервер и заставить врага использовать тотем.
3. ???
4. Краш.

Логи краша:
java.lang.ClassCastException: class thunder.hack.modules.render.PopChams$1 cannot be cast to class net.minecraft.class_742 (thunder.hack.modules.render.PopChams$1 and net.minecraft.class_742 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @64729b1e)
	at net.minecraft.class_591.handler$dfc000$notenoughanimations$setupAnimEnd(class_591.java:552)
	at net.minecraft.class_591.method_17087(class_591.java:179)
	at thunder.hack.modules.render.PopChams.renderEntity(PopChams.java:114)
	at thunder.hack.modules.render.PopChams.lambda$onRender3D$1(PopChams.java:61)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at thunder.hack.modules.render.PopChams.onRender3D(PopChams.java:61)
	at thunder.hack.core.impl.ModuleManager.lambda$onRender3D$2(ModuleManager.java:340)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at thunder.hack.core.impl.ModuleManager.onRender3D(ModuleManager.java:340)
	at net.minecraft.class_757.handler$ebe000$thunderhack$render3dHook(class_757.java:9686)
	at net.minecraft.class_757.method_3188(class_757.java:1118)
	at net.minecraft.class_757.method_3192(class_757.java:858)
	at net.minecraft.class_310.method_1523(class_310.java:1320)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

Полные логи: https://mclo.gs/PgvBfnt

**Comment by Pan4ur** [comment]
стирай notenoughanimations

**Comment by alexsovi** [comment]
бля, как я это не заметил сразу)
