### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Sat4nHunter1997** [Pan4ur/ThunderHack-Recode#434]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1011.method_4307()" because "this.field_5200" is null
    at net.minecraft.class_1043.method_22793(class_1043.java:24) ~[client-intermediary.jar:?]
    at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:227) ~[client-intermediary.jar:?]
    at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:214) ~[client-intermediary.jar:?]
    at net.minecraft.class_1041.method_15998(class_1041.java:287) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1523(class_310.java:1349) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
    at net.minecraft.client.main.Main.main(Main.java:265) ~[Fabric%201.20.4.jar:?]
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]

**Comment by Zane2b2t** [comment]
this log does not reference anything related to thunderhack
