### ISSUE TITLE
ThudnerGUI + ModulePlate | String#split problem

### ISSUE THREAD

**Issue by TemaFlux** [Pan4ur/ThunderHack-Recode#84]
```
java.lang.NullPointerException: Cannot invoke "String.split(String)" because the return value of "thunder.hack.modules.Module.getDescription()" is null
	at thunder.hack.gui.thundergui.components.ModulePlate.render(ModulePlate.java:137)
	at thunder.hack.gui.thundergui.ThunderGui2.lambda$renderGui$8(ThunderGui2.java:371)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at thunder.hack.gui.thundergui.ThunderGui2.renderGui(ThunderGui2.java:371)
	at thunder.hack.gui.thundergui.ThunderGui2.lambda$render$1(ThunderGui2.java:188)
	at thunder.hack.utility.render.MSAAFramebuffer.use(MSAAFramebuffer.java:62)
	at thunder.hack.utility.render.MSAAFramebuffer.use(MSAAFramebuffer.java:49)
	at thunder.hack.gui.thundergui.ThunderGui2.method_25394(ThunderGui2.java:187)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by Pan4ur** [comment]
fixed
