### ISSUE TITLE
support macos

### ISSUE THREAD

**Issue by waffleaz** [Pan4ur/ThunderHack-Recode#89]
support macos plzzzz
thx :)))

**Comment by 06ED** [comment]
pls send your crashlog

**Comment by waffleaz** [comment]
Below is the log:

[19:26:59] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.14.22
[19:26:59] [main/INFO]: Loading 55 mods:
	- fabric-api 0.89.3+1.20.2
	   |-- fabric-api-base 0.4.33+fce67b32a0
	   |-- fabric-api-lookup-api-v1 1.6.41+fce67b32a0
	   |-- fabric-biome-api-v1 13.0.12+d9a2869ba0
	   |-- fabric-block-api-v1 1.0.12+73761d2ea0
	   |-- fabric-block-view-api-v2 1.0.1+73761d2ea0
	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0
	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0
	   |-- fabric-command-api-v1 1.2.36+f71b366fa0
	   |-- fabric-command-api-v2 2.2.15+86b12645a0
	   |-- fabric-commands-v0 0.2.53+df3654b3a0
	   |-- fabric-containers-v0 0.1.72+df3654b3a0
	   |-- fabric-content-registries-v0 5.0.4+285022b3a0
	   |-- fabric-convention-tags-v1 1.5.7+f4b7e424a0
	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0
	   |-- fabric-data-generation-api-v1 13.1.2+d19c4129a0
	   |-- fabric-dimensions-v1 2.1.56+b1229956a0
	   |-- fabric-entity-events-v1 1.5.25+f4b7e424a0
	   |-- fabric-events-interaction-v0 0.6.9+daef22a2a0
	   |-- fabric-events-lifecycle-v0 0.2.68+df3654b3a0
	   |-- fabric-game-rule-api-v1 1.0.40+f4b7e424a0
	   |-- fabric-item-api-v1 2.1.32+43511215a0
	   |-- fabric-item-group-api-v1 4.0.13+f4b7e424a0
	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0
	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0
	   |-- fabric-lifecycle-events-v1 2.2.26+3bafade3a0
	   |-- fabric-loot-api-v2 2.0.2+0ba8e9cea0
	   |-- fabric-message-api-v1 6.0.1+e982ae85a0
	   |-- fabric-mining-level-api-v1 2.1.54+f4b7e424a0
	   |-- fabric-model-loading-api-v1 1.0.5+f4b7e424a0
	   |-- fabric-models-v0 0.4.4+9386d8a7a0
	   |-- fabric-networking-api-v1 3.0.8+b18afef3a0
	   |-- fabric-object-builder-api-v1 12.1.1+b1b4f7b0a0
	   |-- fabric-particles-v1 1.1.4+f4b7e424a0
	   |-- fabric-recipe-api-v1 2.0.5+96509552a0
	   |-- fabric-registry-sync-v0 4.0.3+34a3e0e2a0
	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0
	   |-- fabric-renderer-indigo 1.5.1+2034447ca0
	   |-- fabric-renderer-registries-v1 3.2.48+df3654b3a0
	   |-- fabric-rendering-data-attachment-v1 0.3.39+73761d2ea0
	   |-- fabric-rendering-fluids-v1 3.0.30+f4b7e424a0
	   |-- fabric-rendering-v0 1.1.51+df3654b3a0
	   |-- fabric-rendering-v1 3.0.10+86b12645a0
	   |-- fabric-resource-conditions-api-v1 2.3.9+43511215a0
	   |-- fabric-resource-loader-v0 0.11.11+86b12645a0
	   |-- fabric-screen-api-v1 2.0.11+0ba8e9cea0
	   |-- fabric-screen-handler-api-v1 1.3.38+86b12645a0
	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0
	   |-- fabric-transfer-api-v1 3.3.8+109a65e5a0
	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0
	- fabricloader 0.14.22
	- java 17
	- minecraft 1.20.2
	- thunderhack 1.3
	   \-- satin 1.14.0
[19:26:59] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Applications/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:26:59] [main/INFO]: Compatibility level set to JAVA_16
[19:26:59] [main/INFO]: Compatibility level set to JAVA_17
[19:27:01] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache)
[19:27:08] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 314 milliseconds
[19:27:11] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[19:27:12] [Render thread/INFO]: Setting user: HFB_
[19:27:14] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[19:27:15] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[19:27:22] [Render thread/WARN]: Failed to create window: 
net.minecraft.class_1041$class_4716: GLFW error 65548: Cocoa: Regular windows do not have icons on macOS
	at net.minecraft.class_1041.method_4501(class_1041.java:195) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokePPV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.nglfwSetWindowIcon(GLFW.java:2368) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwSetWindowIcon(GLFW.java:2400) ~[lwjgl-glfw-3.3.2.jar:?]
	at net.minecraft.class_310.setWindowIcon(class_310.java:6673) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.redirect$zod000$thunderhack$onChangeIcon(class_310.java:6649) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:500) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:214) ~[1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]

When it opens, it displays a window that says: 
GLFW error 65548: Cocoa: Regular windows do not have icons on macOS.
Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).

**Comment by Pan4ur** [comment]
I'll try to fix it today

**Comment by HenryXiaoYang** [comment]
This is a issue with glfw, you can't possibly fix it. You need a mod called Chameleon to fix the glfw. However, Chameleon's mixin will conflict with ThunderHack's. Specifically, class "onChangeIcon". The minecraft set window icon class had been redirected by both mod, and cause crash.

What I did is that I deleted the redirect of class "onChangeIcon" and the code inside the class.

**Comment by HenryXiaoYang** [comment]
> This is a issue with glfw, you can't possibly fix it. You need a mod called Chameleon to fix the glfw. However, Chameleon's mixin will conflict with ThunderHack's. Specifically, class "onChangeIcon". The minecraft set window icon class had been redirected by both mod, and cause crash.
> 
> What I did is that I deleted the redirect of class "onChangeIcon" and the code inside the class.

Oh, the "onChangeIcon" class is here: src/main/java/thunder/hack/injection/MixinMinecraftClient.java

**Comment by Pan4ur** [comment]
Mb fixed try plz and reply

**Comment by waffleaz** [comment]
It's ready, thx
